// Code generated by schema2code at 2025-10-20 19:10:24. DO NOT EDIT.


/**
 * Context window size and management settings
 */
export interface WindowConfig {
  /**
   * Maximum context window size in tokens
   */
  max_tokens: number;
  /**
   * Tokens to reserve for response generation
   */
  reserve_tokens: number;
  /**
   * Strategy when context exceeds max_tokens
   */
  overflow_strategy: 'truncate_oldest' | 'truncate_middle' | 'compress' | 'error';
}

/**
 * Content prioritization for context assembly
 */
export interface Prioritization {
  /**
   * Priority order for context sources (highest to lowest)
   */
  priority_order: 'recent_messages' | 'retrieved_memories' | 'summaries' | 'search_results' | 'tool_results'[];
  /**
   * Number of recent messages to always include
   */
  recent_messages_count: number;
  /**
   * Fraction of context window allocated to memories
   */
  memory_allocation: number;
  /**
   * Fraction of context window allocated to summaries
   */
  summary_allocation: number;
}

/**
 * Context optimization and efficiency settings
 */
export interface Optimization {
  /**
   * Enable content compression for efficiency
   */
  enable_compression: boolean;
  /**
   * Remove duplicate content across sources
   */
  deduplication: boolean;
  /**
   * Use intelligent truncation preserving key content
   */
  smart_truncation: boolean;
  /**
   * Cache optimized context for reuse
   */
  cache_optimized_context: boolean;
  /**
   * Method for counting tokens
   */
  token_counting_method: 'approximate' | 'precise' | 'model_specific';
}

/**
 * Configuration for context window management and optimization
 */
export interface ContextWindowConfig {
  /**
   * Enable intelligent context window management
   */
  enabled: boolean;
  /**
   * Context window size and management settings
   */
  window_config: WindowConfig;
  /**
   * Content prioritization for context assembly
   */
  prioritization: Prioritization;
  /**
   * Context optimization and efficiency settings
   */
  optimization: Optimization;
}