// Code generated by schema2code at 2025-10-20 19:10:24. DO NOT EDIT.


/**
 * Conversation represents a conversation between a user and the LLM
 */
export interface Conversation {
  /**
   * Unique identifier for the conversation
   */
  id: number;
  /**
   * Id of the user who owns the conversation
   */
  user_id: string;
  /**
   * Title of the conversation
   */
  title: string;
  /**
   * Timestamp of when the conversation was created
   */
  created_at: Date;
  /**
   * Timestamp of when the conversation was last updated
   */
  updated_at: Date;
}