// Code generated by schema2code at 2025-10-20 19:10:25. DO NOT EDIT.


/**
 * Configuration schema for event stream processing
 */
export interface EventStreamConfig {
  /**
   * Initial thinking phase flag
   */
  thinking_phase_initial: boolean;
  /**
   * Maximum content length allowed
   */
  max_content_length: number;
  /**
   * Buffer size for repetition detection in characters
   */
  repetition_buffer_chars: number;
  /**
   * Minimum n-gram size
   */
  ngram_min: number;
  /**
   * Maximum n-gram size
   */
  ngram_max: number;
  /**
   * Number of prior occurrences to consider repetitive
   */
  ngram_repeat_threshold: number;
  /**
   * Window size for stutter detection in words
   */
  stutter_window_words: number;
  /**
   * Threshold for unique ratio in stutter window (≤ 25% unique)
   */
  stutter_unique_ratio_threshold: number;
  /**
   * Maximum allowed repetitions
   */
  max_repetitions: number;
  /**
   * Number of last hashes to keep for deduplication
   */
  dedup_last_hashes: number;
}