// Code generated by schema2code at 2025-10-20 19:10:27. DO NOT EDIT.


/**
 * Metadata for an image generated on the system.
 */
export interface ImageMetadata {
  /**
   * Unique identifier for the image.
   */
  id?: number;
  /**
   * filename (including path) of the image.
   */
  filename: string;
  /**
   * URL or path to the thumbnail version of the image.
   */
  thumbnail: string;
  /**
   * Width of the image in pixels.
   */
  width: number;
  /**
   * Height of the image in pixels.
   */
  height: number;
  /**
   * Format of the image file.
   */
  format: 'jpg' | 'png' | 'gif' | 'bmp' | 'webp' | 'svg';
  /**
   * Unique identifier for the user who the image was generated for.
   */
  user_id: string;
  /**
   * Unique identifier for the conversation associated with the image.
   */
  conversation_id?: number;
  /**
   * Timestamp when the image was created.
   */
  created_at: Date;
  /**
   * URL for viewing the image.
   */
  view_url?: string;
  /**
   * URL for downloading the image.
   */
  download_url?: string;
}