// Code generated by schema2code at 2025-10-20 19:10:28. DO NOT EDIT.


/**
 * Memory retrieval settings for semantic search and embedding operations
 */
export interface MemoryConfig {
  /**
   * Whether memory retrieval is enabled
   */
  enabled: boolean;
  /**
   * Maximum number of memories to retrieve
   */
  limit: number;
  /**
   * Enable cross-user memory retrieval
   */
  enable_cross_user: boolean;
  /**
   * Enable cross-conversation memory retrieval
   */
  enable_cross_conversation: boolean;
  /**
   * Minimum similarity threshold for memory matching (0.0 to 1.0)
   */
  similarity_threshold: number;
  /**
   * Always retrieve memories regardless of query content
   */
  always_retrieve: boolean;
  /**
   * Memory retrieval timeout in seconds
   */
  timeout: number;
}