// Code generated by schema2code at 2025-10-20 19:10:37. DO NOT EDIT.


/**
 * Type of message
 */
export type MessageType = 'connect' | 'connected' | 'pause' | 'paused' | 'resume' | 'resumed' | 'cancel' | 'cancelled' | 'complete' | 'error' | 'warning' | 'info' | 'failed';

/**
 * Constant values for MessageType
 */
export const MessageTypeValues = {
  /** connect */
  CONNECT: 'connect',
  /** connected */
  CONNECTED: 'connected',
  /** pause */
  PAUSE: 'pause',
  /** paused */
  PAUSED: 'paused',
  /** resume */
  RESUME: 'resume',
  /** resumed */
  RESUMED: 'resumed',
  /** cancel */
  CANCEL: 'cancel',
  /** cancelled */
  CANCELLED: 'cancelled',
  /** complete */
  COMPLETE: 'complete',
  /** error */
  ERROR: 'error',
  /** warning */
  WARNING: 'warning',
  /** info */
  INFO: 'info',
  /** failed */
  FAILED: 'failed'
} as const;