// Code generated by schema2code at 2025-10-20 19:10:29. DO NOT EDIT.


/**
 * Type of content in a message or streaming chunk
 */
export type MessageContentType = 'text' | 'image' | 'tool_call' | 'tool_result' | 'image_generation' | 'audio' | 'video' | 'image_edit' | 'file' | 'thinking' | 'error_content' | 'metadata';

/**
 * Constant values for MessageContentType
 */
export const MessageContentTypeValues = {
  /** text */
  TEXT: 'text',
  /** image */
  IMAGE: 'image',
  /** tool_call */
  TOOL_CALL: 'tool_call',
  /** tool_result */
  TOOL_RESULT: 'tool_result',
  /** image_generation */
  IMAGE_GENERATION: 'image_generation',
  /** audio */
  AUDIO: 'audio',
  /** video */
  VIDEO: 'video',
  /** image_edit */
  IMAGE_EDIT: 'image_edit',
  /** file */
  FILE: 'file',
  /** thinking */
  THINKING: 'thinking',
  /** error_content */
  ERROR_CONTENT: 'error_content',
  /** metadata */
  METADATA: 'metadata'
} as const;