// Code generated by schema2code at 2025-10-20 19:10:35. DO NOT EDIT.


/**
 * ModelTask represents the task associated with a machine learning model
 */
export type ModelTask = 'TextToText' | 'TextToImage' | 'ImageToText' | 'ImageToImage' | 'TextToAudio' | 'AudioToText' | 'TextToVideo' | 'VideoToText' | 'TextToSpeech' | 'SpeechToText' | 'TextToEmbeddings' | 'VisionTextToText' | 'ImageTextToImage' | 'TextToRanking';

/**
 * Constant values for ModelTask
 */
export const ModelTaskValues = {
  /** TextToText */
  TEXTTOTEXT: 'TextToText',
  /** TextToImage */
  TEXTTOIMAGE: 'TextToImage',
  /** ImageToText */
  IMAGETOTEXT: 'ImageToText',
  /** ImageToImage */
  IMAGETOIMAGE: 'ImageToImage',
  /** TextToAudio */
  TEXTTOAUDIO: 'TextToAudio',
  /** AudioToText */
  AUDIOTOTEXT: 'AudioToText',
  /** TextToVideo */
  TEXTTOVIDEO: 'TextToVideo',
  /** VideoToText */
  VIDEOTOTEXT: 'VideoToText',
  /** TextToSpeech */
  TEXTTOSPEECH: 'TextToSpeech',
  /** SpeechToText */
  SPEECHTOTEXT: 'SpeechToText',
  /** TextToEmbeddings */
  TEXTTOEMBEDDINGS: 'TextToEmbeddings',
  /** VisionTextToText */
  VISIONTEXTTOTEXT: 'VisionTextToText',
  /** ImageTextToImage */
  IMAGETEXTTOIMAGE: 'ImageTextToImage',
  /** TextToRanking */
  TEXTTORANKING: 'TextToRanking'
} as const;