// Code generated by schema2code at 2025-10-20 19:10:31. DO NOT EDIT.


/**
 * ModelDetails contains additional information about a model
 */
export interface ModelDetails {
  /**
   * Identifier of the parent model if this is a derivative
   */
  parent_model?: string;
  /**
   * Format of the model file (e.g., gguf)
   */
  format: string;
  /**
   * Path to the GGUF file if applicable
   */
  gguf_file?: string;
  /**
   * Primary model family this belongs to (e.g., llama, phi3)
   */
  family: string;
  /**
   * All model families this belongs to
   */
  families: string[];
  /**
   * Size of model parameters (e.g., '7.2B')
   */
  parameter_size: string;
  /**
   * Level of quantization applied to the model (e.g., 'Q4_0')
   */
  quantization_level?: string;
  /**
   * Data type of the model (e.g., 'float16', 'bfloat16')
   */
  dtype?: string;
  /**
   * Precision of the model (e.g., 'fp16', 'bf16')
   */
  precision?: 'fp32' | 'fp16' | 'bf16' | 'int8' | 'int4' | 'int2' | 'int1';
  /**
   * Specialization of the model (e.g., 'LoRA', 'Embedding', 'TextToImage', 'Audio', 'Vision')
   */
  specialization?: 'LoRA' | 'Embedding' | 'TextToImage' | 'ImageToImage' | 'Audio' | 'Text';
  /**
   * Description of the model
   */
  description?: string;
  /**
   * Weight of the model (applies to LoRA models)
   */
  weight?: number;
}