// Code generated by schema2code at 2025-10-20 19:10:35. DO NOT EDIT.


/**
 * Response refinement settings
 */
export interface RefinementConfig {
  /**
   * Enable response filtering
   */
  enable_response_filtering: boolean;
  /**
   * Enable response critique
   */
  enable_response_critique: boolean;
}