// Code generated by schema2code at 2025-10-20 19:10:37. DO NOT EDIT.


/**
 * The current processing stage.
 */
export type SocketStageType = 'initializing' | 'retrieving_memories' | 'searching_web' | 'summarizing' | 'generating_image' | 'processing' | 'rendering' | 'interpreting' | 'open';

/**
 * Constant values for SocketStageType
 */
export const SocketStageTypeValues = {
  /** initializing */
  INITIALIZING: 'initializing',
  /** retrieving_memories */
  RETRIEVING_MEMORIES: 'retrieving_memories',
  /** searching_web */
  SEARCHING_WEB: 'searching_web',
  /** summarizing */
  SUMMARIZING: 'summarizing',
  /** generating_image */
  GENERATING_IMAGE: 'generating_image',
  /** processing */
  PROCESSING: 'processing',
  /** rendering */
  RENDERING: 'rendering',
  /** interpreting */
  INTERPRETING: 'interpreting',
  /** open */
  OPEN: 'open'
} as const;