FROM python:3.10

WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
COPY ./rag_with_ollama.py /app/rag_with_ollama.py

RUN pip3 install -r /app/requirements.txt

CMD ["uvicorn", "main:app","--host","0.0.0.0","--port", "5050", "--reload"]
