"""Add chat_messages table to store conversation content

Revision ID: 002_add_chat_messages
Revises: 001_create_analytics_tables
Create Date: 2025-10-20 11:30:00.000000

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "002_add_chat_messages"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column(
            "message_type",
            sa.String(length=20),
            nullable=False,
            comment="Tipo: user, bot",
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column(
            "sources_used",
            postgresql.ARRAY(sa.Text()),
            nullable=True,
            comment="Fuentes utilizadas para generar respuesta",
        ),
        sa.Column(
            "detected_language",
            sa.String(length=10),
            nullable=True,
            comment="Idioma detectado: es, en, fr, etc.",
        ),
        sa.Column(
            "topics_mentioned",
            postgresql.ARRAY(sa.Text()),
            nullable=True,
            comment="Temas mencionados en el mensaje",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("NOW()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["chat_sessions.session_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chat_messages_created_at", "chat_messages", ["created_at"], unique=False
    )
    op.create_index(
        "idx_chat_messages_session_id", "chat_messages", ["session_id"], unique=False
    )
    op.create_index(
        "idx_chat_messages_type", "chat_messages", ["message_type"], unique=False
    )
    op.create_check_constraint(
        "check_message_type_valid", "chat_messages", "message_type IN ('user', 'bot')"
    )
    op.create_check_constraint(
        "check_response_time_positive", "chat_messages", "response_time_ms >= 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_response_time_positive", "chat_messages", type_="check")
    op.drop_constraint("check_message_type_valid", "chat_messages", type_="check")
    op.drop_index("idx_chat_messages_type", table_name="chat_messages")
    op.drop_index("idx_chat_messages_session_id", table_name="chat_messages")
    op.drop_index("idx_chat_messages_created_at", table_name="chat_messages")
    op.drop_table("chat_messages")
    # ### end Alembic commands ###
