---
# Global exclude pattern - Skip running hooks on alembic migration files
exclude: ^boss_bot/alembic/.*
# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit
ci:
  # Message used when pre-commit auto-fixes issues
  autofix_commit_msg: "style: pre-commit fixes"
  # Whether to auto-fix PRs
  autofix_prs: true
  # Branch to update when auto-updating hooks
  autoupdate_branch: ""
  # Message used when auto-updating hooks
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  # How often to auto-update hooks
  autoupdate_schedule: weekly
  # List of hooks to skip in CI
  skip: []
  # Whether to process git submodules
  submodules: false
default_install_hook_types:
  # Runs before commit is finalized, checks staged changes
  - pre-commit
  # Validates commit messages
  - commit-msg
  # Runs before push operation
  - pre-push
  # Runs after checkout operation
  - post-checkout
  # Runs after merge operation
  - post-merge
default_stages:
  # Run during git commit
  - pre-commit
  # Run during git push
  - pre-push
  # Run during git merge
  - pre-merge-commit
  # Run during git rebase
  - pre-rebase
# TODO: Work with team to see when the right time is to enable this
repos:
  # # Meta hooks for validating pre-commit configuration
  # - repo: meta
  #   hooks:
  #     # Ensures hooks apply to at least one file
  #     - id: check-hooks-apply
  #     # Ensures exclude patterns are valid
  #     - id: check-useless-excludes
  #     # Useful for debugging hook arguments
  #     - id: identity
  #       stages: [pre-commit, manual]

  # Validates pyproject.toml file structure
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        # Optional extra validations from SchemaStore:
        additional_dependencies:
          ["validate-pyproject[all]", "validate-pyproject-schema-store"]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.26.0
    hooks:
      - id: gitleaks

  # Text-related hooks for various formatting tasks
  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.8
    hooks:
      - id: alphabetize-codeowners
      - id: fix-smartquotes
      - id: fix-ligatures

  # # Prettier formatting for YAML and JSON5
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v4.0.0-alpha.8
  #   hooks:
  #     - id: prettier
  #       types_or: [yaml, json5]

  - repo: https://github.com/bossjones/pre-commit-pretty-format-json5
    rev: "86957f50581644a8dd62833bcecbac1bd2c0e135"
    hooks:
      - id: pretty-format-json5
        files: \.vscode/settings\.json$

  # Standard pre-commit hooks for basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Verifies Python syntax
      - id: check-ast
        exclude: (.vscode|contrib)
      # Verifies JSON syntax
      - id: check-json
        exclude: (.vscode|.devcontainer|hack|cookbook|ai_docs)
      - id: detect-private-key # checks for private keys (BEGIN X PRIVATE KEY, etc.)
      - id: pretty-format-json # cleaner json files
        args: ["--autofix"] # automatically
        files: ^pyrightconfig\.json$

  # Python import sorting for aio_settings.py
  - repo: https://github.com/bwhmather/ssort
    rev: 0.14.0
    hooks:
      - id: ssort
        files: ^.*increase_version_number\.py$

  # When running with --fix, Ruff's lint hook should be placed before Ruff's formatter hook, and before Black, isort, and other formatting tools, as Ruff's fix behavior can output code changes that require reformatting.
  # SOURCE: https://github.com/astral-sh/ruff-pre-commit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      # Ruff linter
      - id: ruff
        # entry: ruff check --force-exclude
        args:
          - --fix
          - --exit-non-zero-on-fix
          - --show-fixes
          - --config=pyproject.toml
        # SOURCE: https://github.com/girder/large_image/blob/2e6fd90cfb9179f2c0bd59031f45805018f3f04a/.pre-commit-config.yaml
        types_or:
          - python
          # - jupyter
        exclude: ^(justfiles|typings)/.*

      # Ruff formatter
      - id: ruff-format
        # entry: ruff format --force-exclude
        types_or:
          - python
        args:
          - --config=pyproject.toml
        files: ^((src|tests|notebooks)/.+)?[^/]+\.(py|ipynb)$
        exclude: (justfiles|hack)

  # Additional pre-commit hooks for file integrity checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Check for case conflicts in filenames
      - id: check-case-conflict
      # Check for merge conflict markers
      - id: check-merge-conflict
      # Check for broken symlinks
      - id: check-symlinks
      # Ensure files end with a newline
      - id: end-of-file-fixer
        exclude: (.*\.pyi$)
      # Check for mixed line endings
      - id: mixed-line-ending
        exclude: (.*\.pyi$)
      # Remove trailing whitespace
      - id: trailing-whitespace
        exclude: (.*\.pyi$)
  ##########################################################################################
  # #  # NOTE: if we are going to use this, it needs to run AFTER ruff.
  ##########################################################################################

  # SOURCE:https://github.com/humblFINANCE/humblAPI/blob/master/.pre-commit-config.yaml
  # SOURCE: https://github.com/pypa/pip/blob/main/.pre-commit-config.yaml
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      # Prevent use of deprecated logging.warn
      - id: python-no-log-warn
      # Check for Unicode replacement characters
      - id: text-unicode-replacement-char

  # Local hooks that run commands directly on the system
  - repo: local
    hooks:
      # Custom hook to detect pytest live logging configuration
      - id: detect-pytest-live-log
        name: detect-pytest-live-log
        entry: bash -x ./detect_pytest_live_logging.sh
        language: system
        types:
          - toml
        files: ^pyproject.*$

  # Python docstring formatting
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
        args:
          - --style {numpydoc,pep257}
          - --no-strip-whitespace
          - --no-capitalize-first-letter
        files: ^((src|tests|notebooks)/.+)?[^/]+\.(py|ipynb)$
        exclude: (justfiles|hack)

  # Automatically upgrade Python syntax
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
          - --keep-runtime-typing

  # # Changelog management with towncrier
  # - repo: https://github.com/twisted/towncrier
  #   rev: 24.8.0
  #   hooks:
  #     # Check if news fragments are properly formatted
  #     - id: towncrier-check
  #       entry: uv run towncrier --draft
  #       files: changes/
  #     # # Update changelog from news fragments
  #     # - id: towncrier-update
  #     #   entry: uv run towncrier
  #     #   files: changes/
  #     #   args:
  #     - --keep

  # JSON Schema validation for GitHub workflows
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
      # Validate GitHub workflow files
      - id: check-github-workflows
        exclude: (justfiles|hack|.github/workflows/_python-vulnerability-scan.yml)
      # Validate ReadTheDocs configuration
      - id: check-readthedocs

  # SOURCE: https://github.com/kiwicom/pytest-recording/tree/master
  - repo: https://github.com/codingjoe/relint
    rev: 3.3.1
    hooks:
      - id: relint
        args:
          - --config=.relint.yml
          - --diff

  # Commitizen for standardizing commit messages
  - repo: https://github.com/commitizen-tools/commitizen
    rev: "v4.8.2"
    hooks:
      # Check commit message format
      - id: commitizen
      # Check branch naming convention
      - id: commitizen-branch
        stages: [pre-push]

  # # TOML file sorting
  # - repo: https://github.com/pappasam/toml-sort
  #   rev: v0.24.2
  #   hooks:
  #     # Sort pyproject.toml sections
  #     - id: toml-sort-fix
  #       files: pyproject.toml

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        entry: taplo fmt
        args:
          - --config=taplo.toml
          - --diff
      - id: taplo-lint
        entry: taplo lint
        args:
          - --config=taplo.toml
          - --default-schema-catalogs
          - --schema=taplo://taplo.toml
        files: taplo.toml
      - id: taplo-lint
        entry: taplo lint
        args:
          - --config=taplo.toml
          - --default-schema-catalogs
          - --schema=https://json.schemastore.org/pyproject.json
        files: pyproject.toml
      - id: taplo-lint
        entry: taplo lint
        args:
          - --config=taplo.toml
          - --default-schema-catalogs
        files: mise.toml
  # Additional pyproject.toml validation
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        # Optional extra validations from SchemaStore:
        additional_dependencies:
          ["validate-pyproject[all]", "validate-pyproject-schema-store"]

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.7
    hooks:
      - id: markdown-link-check
        args: [--quiet]

  # ------------------------------------------------------------------------
  # SOURCE: https://github.com/tektronix/python-package-ci-cd/blob/d2d47156cfbdcfe561bbf49fe9fa10e8e623a500/.pre-commit-config.yaml
  # ------------------------------------------------------------------------
  # - repo: https://github.com/renovatebot/pre-commit-hooks
  #   rev: ba23a9813b5f8208751027695609272732db82be  # frozen: 39.227.1
  #   hooks:
  #     - id: renovate-config-validator
  #       language_version: 20.18.0  # TODO: remove this line once https://github.com/renovatebot/pre-commit-hooks/issues/2460 is resolved
  # - repo: https://github.com/python-jsonschema/check-jsonschema
  #   rev: a167de9d5f4e87e1cdb16cb560aa704b79b6f655  # frozen: 0.32.1
  #   hooks:
  #     - id: check-dependabot
  #     - id: check-github-actions
  #       files: action\.(yml|yaml)
  #     - id: check-github-workflows
  #       args: [--verbose]
  #       files: ^(\.github/workflows/[^/]+|workflows/[^/]+)$
  # - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
  #   rev: a185be0fd5b45112845b700d91b81050c75579e2  # frozen: v1.7.7.23
  #   hooks:
  #     - id: actionlint
  #       additional_dependencies: [pyflakes, shellcheck-py]
  # ------------------------------------------------------------------------

  # - repo: https://github.com/woodruffw/zizmor-pre-commit
  #   rev: v1.5.1
  #   hooks:
  #     - id: zizmor
