name: docs

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches: [main, "gh-pages"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt install -y --no-install-recommends \
            build-essential \
            curl \
            python3-venv \
            cmake \
            zsh \
            git

      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1

  tests:
    needs: [pre-commit]
    name: "pytest"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt install -y --no-install-recommends \
            build-essential \
            curl \
            python3-venv \
            cmake \
            zsh

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install extra dependencies
        run: uv sync --dev

  deploy-docs:
    needs: [tests]
    name: "Deploy documentation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install extra dependencies
        run: uv sync --dev

      - name: Build documentation
        run: uv run mkdocs gh-deploy --force

      # SOURCE: https://github.com/HYP3R00T/Rosetta/blob/e02fd400b94972a3f0529dbfaed7a55f72a5cade/Notes/Technology/Publish%20MkDocs%20using%20GitHub%20Action%20and%20uv.md?plain=1#L32
      - name: Build and deploy documentation
        run: |
          uv run mkdocs build --verbose
          uv run mkdocs gh-deploy --verbose --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
