LABEL_MAPPINGS = {
    'Apple_scab': 'scab',
    'Bacterial_spot': 'Bacterial_spot',
    'Black_rot': 'Fruit borer',
    'Cedar_apple_rust': 'Rust',
    'Cercospora_leaf_spot Gray_leaf_spot': 'Alternaria_leaf_blotch',
    'Common_rust': 'Rust',
    'Early_blight': 'Fire_blight',
    'Esca_(Black_Measles)': 'Blossom_thrips',
    'Haunglongbing_(Citrus_greening)': 'Crown_gall',
    'Late_blight': 'Fire_blight',
    'Leaf_Mold': 'Codling_moth',
    'Leaf_blight_(Isariopsis_Leaf_Spot)': 'Fire_blight',
    'Leaf_scorch': 'Alternaria_leaf_blotch',
    'Northern_Leaf_Blight': 'Fire_blight',
    'Powdery_mildew': 'Powdery_mildew',
    'Septoria_leaf_spot': 'San_Jose_scale',
    'Spider_mites Two-spotted_spider_mite': 'European_red_mite',
    'Target_Spot': 'stem_borer',
    'Tomato_Yellow_Leaf_Curl_Virus': 'Tent_caterpillar',
    'Tomato_mosaic_virus': 'mosaic_virus',
    'Unknown': 'Unknown',
    'healthy': 'healthy'
}
