# Code generated by schema2code at 2025-10-20 19:10:43. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .complexity_level import ComplexityLevel
from .computational_requirement import ComputationalRequirement
from .model_profile_type import ModelProfileType
from .required_capability import RequiredCapability
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class CapabilityProfileMapping(BaseModel):
    """Mapping from required capabilities to appropriate model profile types"""
    capability: RequiredCapability = Field(..., description="The required capability")
    """The required capability"""
    compatible_profiles: List[ModelProfileType] = Field(..., description="List of model profile types that can fulfill this capability")
    """List of model profile types that can fulfill this capability"""
    preferred_profile: ModelProfileType = Field(..., description="Preferred model profile type for this capability")
    """Preferred model profile type for this capability"""
    minimum_complexity_level: Optional[ComplexityLevel] = Field(default=None, description="Minimum complexity level where this capability mapping applies")
    """Minimum complexity level where this capability mapping applies"""
    computational_requirements: Optional[List[ComputationalRequirement]] = Field(default=None, description="Computational requirements imposed by this capability")
    """Computational requirements imposed by this capability"""

    class Config:
        extra = "ignore"