# Code generated by schema2code at 2025-10-20 19:10:43. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .message import Message
from .message_content import MessageContent
from .message_content_type import MessageContentType
from .message_role import MessageRole
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ChatResponse(BaseModel):
    """ChatResponse represents a response from the chat API"""
    done: bool = Field(..., description="Indicates whether the generation is complete")
    """Indicates whether the generation is complete"""
    message: Optional[Message] = Field(default=None, description="The message content and metadata returned by the model")
    """The message content and metadata returned by the model"""
    created_at: Optional[datetime] = Field(default=None, description="Timestamp when the response was created")
    """Timestamp when the response was created"""
    context: Optional[List[List[float]]] = Field(default=None, description="Vectors representing the tokenized context (embeddings)")
    """Vectors representing the tokenized context (embeddings)"""
    finish_reason: Optional[str] = Field(default=None, description="Specific indicator of how or why the generation finished")
    """Specific indicator of how or why the generation finished"""
    total_duration: Optional[float] = Field(default=None, description="Total time taken for the entire generation process in milliseconds")
    """Total time taken for the entire generation process in milliseconds"""
    load_duration: Optional[float] = Field(default=None, description="Time taken to load the model in milliseconds")
    """Time taken to load the model in milliseconds"""
    prompt_eval_count: Optional[float] = Field(default=None, description="Number of tokens in the prompt that were evaluated")
    """Number of tokens in the prompt that were evaluated"""
    prompt_eval_duration: Optional[float] = Field(default=None, description="Time taken to evaluate the prompt tokens in milliseconds")
    """Time taken to evaluate the prompt tokens in milliseconds"""
    eval_count: Optional[float] = Field(default=None, description="Total number of tokens evaluated")
    """Total number of tokens evaluated"""
    eval_duration: Optional[float] = Field(default=None, description="Time taken for token evaluation in milliseconds")
    """Time taken for token evaluation in milliseconds"""
    thinking: Optional[str] = Field(default=None, description="The thinking/reasoning process from the assistant before the response")
    """The thinking/reasoning process from the assistant before the response"""
    channels: Optional[Dict[str, Any]] = Field(default=None, description="Additional structured channels extracted from the response (tool calls, status, etc.)")
    """Additional structured channels extracted from the response (tool calls, status, etc.)"""
    observer_messages: Optional[List[str]] = Field(default=None, description="OBSERVER role messages that should be displayed as temporary floating notifications")
    """OBSERVER role messages that should be displayed as temporary floating notifications"""

    class Config:
        extra = "ignore"