# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class CircuitBreakerConfig(BaseModel):
    """Configuration for circuit breaker and timeout protection"""
    base_timeout: Optional[float] = Field(default=None, description="Base timeout in seconds", ge=1.0, le=600.0)
    """Base timeout in seconds"""
    deep_research_timeout: Optional[float] = Field(default=None, description="Extended timeout for deep research tasks", ge=1.0, le=1200.0)
    """Extended timeout for deep research tasks"""
    max_retries: Optional[int] = Field(default=None, description="Maximum number of retries before giving up", ge=0, le=10)
    """Maximum number of retries before giving up"""
    cooldown_period: Optional[float] = Field(default=None, description="Time in seconds before allowing retry after failure", ge=0.0, le=300.0)
    """Time in seconds before allowing retry after failure"""
    enable_perplexity_guard: Optional[bool] = Field(default=None, description="Enable or disable perplexity-based quality monitoring")
    """Enable or disable perplexity-based quality monitoring"""
    enable_repetition_detection: Optional[bool] = Field(default=None, description="Enable or disable repetition detection entirely")
    """Enable or disable repetition detection entirely"""
    perplexity_window: Optional[int] = Field(default=None, description="Number of tokens to consider when calculating perplexity", ge=10, le=200)
    """Number of tokens to consider when calculating perplexity"""
    perplexity_threshold: Optional[float] = Field(default=None, description="Perplexity threshold above which to trigger quality concerns", ge=1.0, le=50.0)
    """Perplexity threshold above which to trigger quality concerns"""
    avg_logprob_floor: Optional[float] = Field(default=None, description="Minimum average log probability threshold", ge=-20.0, le=0.0)
    """Minimum average log probability threshold"""
    repetition_ngram: Optional[int] = Field(default=None, description="N-gram size for repetition detection", ge=2, le=20)
    """N-gram size for repetition detection"""
    repetition_threshold: Optional[int] = Field(default=None, description="Number of repetitions before triggering detection", ge=2, le=20)
    """Number of repetitions before triggering detection"""
    min_tokens_for_eval: Optional[int] = Field(default=None, description="Minimum number of tokens before starting quality evaluation", ge=5, le=500)
    """Minimum number of tokens before starting quality evaluation"""
    perplexity_log_interval_tokens: Optional[int] = Field(default=None, description="Interval in tokens for logging perplexity metrics", ge=5, le=100)
    """Interval in tokens for logging perplexity metrics"""
    log_repetition_events: Optional[bool] = Field(default=None, description="Whether to log repetition detection events")
    """Whether to log repetition detection events"""
    tool_gen_repetition_ngram: Optional[int] = Field(default=None, description="N-gram size for tool generation repetition detection", ge=2, le=20)
    """N-gram size for tool generation repetition detection"""
    tool_gen_repetition_threshold: Optional[int] = Field(default=None, description="Number of repetitions before triggering tool generation detection", ge=2, le=20)
    """Number of repetitions before triggering tool generation detection"""

    class Config:
        extra = "ignore"