# Code generated by schema2code at 2025-10-20 19:10:45. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class WindowConfig(BaseModel):
    """Context window size and management settings"""
    max_tokens: int = Field(default=8192, description="Maximum context window size in tokens", ge=1024, le=32768)
    """Maximum context window size in tokens"""
    reserve_tokens: int = Field(default=1024, description="Tokens to reserve for response generation", ge=256, le=4096)
    """Tokens to reserve for response generation"""
    overflow_strategy: str = Field(default='truncate_oldest', description="Strategy when context exceeds max_tokens")
    """Strategy when context exceeds max_tokens"""

    class Config:
        extra = "ignore"

class Prioritization(BaseModel):
    """Content prioritization for context assembly"""
    priority_order: List[str] = Field(default_factory=lambda: ['recent_messages', 'retrieved_memories', 'summaries', 'search_results', 'tool_results'], description="Priority order for context sources (highest to lowest)")
    """Priority order for context sources (highest to lowest)"""
    recent_messages_count: int = Field(default=5, description="Number of recent messages to always include", ge=1, le=20)
    """Number of recent messages to always include"""
    memory_allocation: float = Field(default=0.3, description="Fraction of context window allocated to memories", ge=0.1, le=0.7)
    """Fraction of context window allocated to memories"""
    summary_allocation: float = Field(default=0.2, description="Fraction of context window allocated to summaries", ge=0.1, le=0.5)
    """Fraction of context window allocated to summaries"""

    class Config:
        extra = "ignore"

class Optimization(BaseModel):
    """Context optimization and efficiency settings"""
    enable_compression: bool = Field(default=True, description="Enable content compression for efficiency")
    """Enable content compression for efficiency"""
    deduplication: bool = Field(default=True, description="Remove duplicate content across sources")
    """Remove duplicate content across sources"""
    smart_truncation: bool = Field(default=True, description="Use intelligent truncation preserving key content")
    """Use intelligent truncation preserving key content"""
    cache_optimized_context: bool = Field(default=True, description="Cache optimized context for reuse")
    """Cache optimized context for reuse"""
    token_counting_method: str = Field(default='approximate', description="Method for counting tokens")
    """Method for counting tokens"""

    class Config:
        extra = "ignore"

class ContextWindowConfig(BaseModel):
    """Configuration for context window management and optimization"""
    enabled: bool = Field(default=True, description="Enable intelligent context window management")
    """Enable intelligent context window management"""
    window_config: WindowConfig = Field(..., description="Context window size and management settings")
    """Context window size and management settings"""
    prioritization: Prioritization = Field(..., description="Content prioritization for context assembly")
    """Content prioritization for context assembly"""
    optimization: Optimization = Field(..., description="Context optimization and efficiency settings")
    """Context optimization and efficiency settings"""

    class Config:
        extra = "ignore"