# Code generated by schema2code at 2025-10-20 19:10:57. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class DevStats(BaseModel):
    """Schema representing device memory statistics."""
    id: str = Field(..., description="Device identifier.")
    """Device identifier."""
    uuid: str = Field(..., description="Universally unique identifier for the device.")
    """Universally unique identifier for the device."""
    gpu_util: float = Field(..., description="GPU utilization percentage.")
    """GPU utilization percentage."""
    mem_util: float = Field(..., description="Memory utilization percentage.")
    """Memory utilization percentage."""
    mem_total: float = Field(..., description="Total memory in megabytes.")
    """Total memory in megabytes."""
    mem_used: float = Field(..., description="Used memory in megabytes.")
    """Used memory in megabytes."""
    mem_free: float = Field(..., description="Free memory in megabytes.")
    """Free memory in megabytes."""
    driver: str = Field(..., description="Driver version.")
    """Driver version."""
    name: str = Field(..., description="Device name.")
    """Device name."""
    serial: str = Field(..., description="Device serial number.")
    """Device serial number."""
    display_mode: str = Field(..., description="Display mode status.")
    """Display mode status."""
    display_active: str = Field(..., description="Display active status.")
    """Display active status."""
    temperature: float = Field(..., description="Device temperature in Celsius.")
    """Device temperature in Celsius."""

    class Config:
        extra = "ignore"