# Code generated by schema2code at 2025-10-20 19:10:58. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class EmbeddingResponse(BaseModel):
    """Represents the response for an embedding request"""
    model: str = Field(...)
    embeddings: List[List[float]] = Field(...)
    total_duration: int = Field(...)
    load_duration: int = Field(...)
    prompt_eval_count: int = Field(...)

    class Config:
        extra = "ignore"