# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ImageGenerateRequest(BaseModel):
    """Request for generating an image"""
    prompt: str = Field(..., description="The prompt for image generation")
    """The prompt for image generation"""
    width: Optional[int] = Field(default=None, description="Width of the generated image")
    """Width of the generated image"""
    height: Optional[int] = Field(default=None, description="Height of the generated image")
    """Height of the generated image"""
    inference_steps: Optional[int] = Field(default=None, description="Number of inference steps")
    """Number of inference steps"""
    guidance_scale: Optional[float] = Field(default=None, description="Guidance scale for image generation")
    """Guidance scale for image generation"""
    low_memory_mode: Optional[bool] = Field(default=None, description="Whether to use low memory mode")
    """Whether to use low memory mode"""
    negative_prompt: Optional[str] = Field(default=None, description="Negative prompt for image generation")
    """Negative prompt for image generation"""
    model: str = Field(..., description="Model to use for image generation")
    """Model to use for image generation"""
    loras: Optional[List[str]] = Field(default=None, description="List of LoRA models to apply to the image generation")
    """List of LoRA models to apply to the image generation"""
    image_id: Optional[int] = Field(default=None, description="ID of the image to use as a base for image generation (for img2img)")
    """ID of the image to use as a base for image generation (for img2img)"""
    url: Optional[str] = Field(default=None, description="URL of the image to use as a base for image generation (for img2img)")
    """URL of the image to use as a base for image generation (for img2img)"""
    filename: Optional[str] = Field(default=None, description="Name of the file to save the generated image as")
    """Name of the file to save the generated image as"""

    class Config:
        extra = "ignore"