# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ImageGenerationConfig(BaseModel):
    """Image generation configuration"""
    enabled: bool = Field(..., description="Whether image generation is enabled")
    """Whether image generation is enabled"""
    storage_directory: str = Field(..., description="Directory for file storage")
    """Directory for file storage"""
    max_image_size: int = Field(..., description="Maximum number of pixels in width or height (whichever is greater) for generated images", ge=128, le=4096)
    """Maximum number of pixels in width or height (whichever is greater) for generated images"""
    retention_hours: int = Field(..., description="Retention period for generated images in hours (e.g., 720 for 30 days)", ge=1, le=720)
    """Retention period for generated images in hours (e.g., 720 for 30 days)"""
    auto_prompt_refinement: bool = Field(..., description="Whether to enable automatic prompt refinement for image generation. This will take the given prompt and attempt to refine it to improve the quality of the generated image.")
    """Whether to enable automatic prompt refinement for image generation. This will take the given prompt and attempt to refine it to improve the quality of the generated image."""
    width: int = Field(..., description="Width of the generated image")
    """Width of the generated image"""
    height: int = Field(..., description="Height of the generated image")
    """Height of the generated image"""
    inference_steps: int = Field(..., description="Number of inference steps")
    """Number of inference steps"""
    guidance_scale: float = Field(..., description="Guidance scale for image generation")
    """Guidance scale for image generation"""
    low_memory_mode: bool = Field(..., description="Whether to use low memory mode")
    """Whether to use low memory mode"""
    negative_prompt: str = Field(..., description="Negative prompt for image generation")
    """Negative prompt for image generation"""

    class Config:
        extra = "ignore"