# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ImageGenerateResponse(BaseModel):
    """Response from generating an image"""
    image: str = Field(..., description="Base64-encoded image")
    """Base64-encoded image"""
    download: str = Field(..., description="URL to download the image")
    """URL to download the image"""

    class Config:
        extra = "ignore"