# Code generated by schema2code at 2025-10-20 19:10:58. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .inference_service import InferenceService
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class InferenceServiceConfig(BaseModel):
    """Inference services configuration"""
    ollama: InferenceService = Field(...)
    stable_diffusion: InferenceService = Field(...)
    host: str = Field(..., description="Host for the inference service")
    """Host for the inference service"""
    port: int = Field(..., description="Port for the inference service")
    """Port for the inference service"""

    class Config:
        extra = "ignore"