# Code generated by schema2code at 2025-09-19 14:17:29. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat


class LangChainMessage(BaseModel):
    """Base abstract message class. Messages are the inputs and outputs of ChatModels."""

    content: Union[str, List[Union[str, Dict[str, Any]]]] = Field(
        ..., description="The string contents of the message."
    )
    """The string contents of the message."""
    additional_kwargs: Optional[Dict[str, Any]] = Field(
        default_factory=lambda: {},
        description="Reserved for additional payload data associated with the message.",
    )
    """Reserved for additional payload data associated with the message."""
    response_metadata: Optional[Dict[str, Any]] = Field(
        default_factory=lambda: {},
        description="Response metadata. For example: response headers, logprobs, token counts, model name.",
    )
    """Response metadata. For example: response headers, logprobs, token counts, model name."""
    type: str = Field(
        default="text",
        description="The type of the message. Must be a string that is unique to the message type.",
    )
    """The type of the message. Must be a string that is unique to the message type."""
    name: Optional[str] = Field(
        default=None, description="An optional name for the message."
    )
    """An optional name for the message."""
    id: Optional[str] = Field(
        default=None, description="An optional unique identifier for the message."
    )
    """An optional unique identifier for the message."""
    tool_calls: Optional[List[Dict[str, Any]]] = Field(
        default=None, description="Tool calls associated with the message."
    )
    """Tool calls associated with the message."""

    class Config:
        extra = "ignore"
