# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .message_role import MessageRole
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class MemoryFragment(BaseModel):
    """Content item that is similar to a user's query"""
    id: int = Field(..., description="Unique identifier for the memory fragment")
    """Unique identifier for the memory fragment"""
    role: MessageRole = Field(..., description="Role of the message (e.g., 'user', 'assistant')")
    """Role of the message (e.g., 'user', 'assistant')"""
    content: Optional[str] = Field(default=None, description="Content of the message")
    """Content of the message"""
    embeddings: Optional[List[List[float]]] = Field(default=None, description="Embedding vector representing the memory")
    """Embedding vector representing the memory"""

    class Config:
        extra = "ignore"