# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .message_content_type import MessageContentType
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class MessageContent(BaseModel):
    """Content of a message in a chat conversation"""
    type: MessageContentType = Field(..., description="Type of the message content (e.g., text, image, tool call)")
    """Type of the message content (e.g., text, image, tool call)"""
    text: Optional[str] = Field(default=None, description="Text content of the message, if applicable")
    """Text content of the message, if applicable"""
    url: Optional[str] = Field(default=None, description="URL of the image or resource, if applicable")
    """URL of the image or resource, if applicable"""

    class Config:
        extra = "ignore"