# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ModelProfileImageSettings(BaseModel):
    """ModelProfileImageSettings represents the image settings for a model profile"""
    height: Optional[int] = Field(default=None, description="Height of the image in pixels")
    """Height of the image in pixels"""
    width: Optional[int] = Field(default=None, description="Width of the image in pixels")
    """Width of the image in pixels"""
    inference_steps: Optional[int] = Field(default=None, description="Number of inference steps")
    """Number of inference steps"""
    guidance_scale: Optional[float] = Field(default=None, description="Guidance scale for image generation")
    """Guidance scale for image generation"""
    low_memory_mode: Optional[bool] = Field(default=None, description="Whether to use low memory mode")
    """Whether to use low memory mode"""
    negative_prompt: Optional[str] = Field(default=None, description="Negative prompt for image generation")
    """Negative prompt for image generation"""
    lora_model: Optional[str] = Field(default=None, description="Name of the LoRA model to use for image generation")
    """Name of the LoRA model to use for image generation"""

    class Config:
        extra = "ignore"