# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class PaginationSchema(BaseModel):
    """Schema defining pagination parameters and metadata for API responses"""
    total_count: int = Field(..., description="Total number of items available", ge=0)
    """Total number of items available"""
    limit: int = Field(..., description="Maximum number of items per page", ge=1)
    """Maximum number of items per page"""
    offset: int = Field(..., description="Starting position of the current page", ge=0)
    """Starting position of the current page"""
    has_more: bool = Field(..., description="Indicates whether more items are available beyond the current page")
    """Indicates whether more items are available beyond the current page"""

    class Config:
        extra = "ignore"