# Code generated by schema2code at 2025-09-29 09:55:50. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .research_question import ResearchQuestion
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ResearchPlan(BaseModel):
    """Plan for executing a research task"""
    main_intent: str = Field(..., description="Main intent or goal of the research")
    """Main intent or goal of the research"""
    sub_questions: List[ResearchQuestion] = Field(..., description="Sub-questions to investigate as part of the research")
    """Sub-questions to investigate as part of the research"""
    raw_plan: Optional[str] = Field(default=None, description="Original plan text from LLM")
    """Original plan text from LLM"""

    class Config:
        extra = "ignore"