# Code generated by schema2code at 2025-10-20 19:11:04. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .research_question import ResearchQuestion
from .research_question_result import ResearchQuestionResult
from .research_task_status import ResearchTaskStatus
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ResearchSubtask(BaseModel):
    """Subtask within a research task"""
    id: int = Field(..., description="Unique identifier for the subtask")
    """Unique identifier for the subtask"""
    task_id: int = Field(..., description="Id of the parent research task")
    """Id of the parent research task"""
    question: Optional[ResearchQuestion] = Field(default=None, description="The research question this subtask addresses")
    """The research question this subtask addresses"""
    result: Optional[ResearchQuestionResult] = Field(default=None, description="Synthesized result of the subtask")
    """Synthesized result of the subtask"""
    status: ResearchTaskStatus = Field(..., description="Current status of the subtask")
    """Current status of the subtask"""
    error_message: Optional[str] = Field(default=None, description="Error message if subtask failed")
    """Error message if subtask failed"""
    created_at: datetime = Field(..., description="Timestamp of when the subtask was created")
    """Timestamp of when the subtask was created"""
    updated_at: datetime = Field(..., description="Timestamp of when the subtask was last updated")
    """Timestamp of when the subtask was last updated"""

    class Config:
        extra = "ignore"