# Code generated by schema2code at 2025-10-20 19:11:11. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ResourceUsage(BaseModel):
    """Resource usage metrics for operations"""
    cpu_percent: Optional[float] = Field(default=None, description="CPU usage percentage", ge=0, le=100)
    """CPU usage percentage"""
    memory_mb: Optional[float] = Field(default=None, description="Memory usage in MB", ge=0)
    """Memory usage in MB"""
    gpu_memory_mb: Optional[float] = Field(default=None, description="GPU memory usage in MB", ge=0)
    """GPU memory usage in MB"""
    disk_io_mb: Optional[float] = Field(default=None, description="Disk I/O in MB", ge=0)
    """Disk I/O in MB"""
    network_io_mb: Optional[float] = Field(default=None, description="Network I/O in MB", ge=0)
    """Network I/O in MB"""

    class Config:
        extra = "ignore"