# Code generated by schema2code at 2025-10-20 19:11:06. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .workflow_type import WorkflowType
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class AlternativeStrategy(BaseModel):
    """Alternative routing strategy that was considered"""
    workflows: Optional[List[str]] = Field(default=None)
    strategy: Optional[str] = Field(default=None)
    reason: Optional[str] = Field(default=None)
    confidence: Optional[float] = Field(default=None)

    class Config:
        extra = "ignore"

class Metadata(BaseModel):
    """Additional metadata about the routing decision"""
    workflow_type: Optional[WorkflowType] = Field(default=None, description="Identified primary workflow type from intent analysis")
    """Identified primary workflow type from intent analysis"""
    complexity_level: Optional[str] = Field(default=None, description="Assessed complexity level")
    """Assessed complexity level"""
    fallback_applied: Optional[bool] = Field(default=False, description="Whether fallback routing was applied")
    """Whether fallback routing was applied"""
    routing_path: Optional[List[str]] = Field(default=None, description="Path of routing decisions taken")
    """Path of routing decisions taken"""

    class Config:
        extra = "ignore"

class RoutingStrategy(BaseModel):
    """Strongly typed routing strategy result containing workflow selection and execution details"""
    selected_workflows: List[str] = Field(..., description="List of workflow names selected for execution")
    """List of workflow names selected for execution"""
    execution_strategy: str = Field(..., description="Strategy for executing the selected workflows")
    """Strategy for executing the selected workflows"""
    reason: str = Field(..., description="Explanation for why this routing strategy was chosen")
    """Explanation for why this routing strategy was chosen"""
    confidence: Optional[float] = Field(default=0.8, description="Confidence score for the routing decision (0.0 to 1.0)", ge=0.0, le=1.0)
    """Confidence score for the routing decision (0.0 to 1.0)"""
    metadata: Optional[Metadata] = Field(default=None, description="Additional metadata about the routing decision")
    """Additional metadata about the routing decision"""
    target_node: Optional[str] = Field(default=None, description="Target node name for LangGraph conditional routing")
    """Target node name for LangGraph conditional routing"""
    alternatives: Optional[List[AlternativeStrategy]] = Field(default=None, description="Alternative routing strategies that were considered")
    """Alternative routing strategies that were considered"""

    class Config:
        extra = "ignore"