# Code generated by schema2code at 2025-10-20 19:11:07. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ServerConfig(BaseModel):
    """Server configuration"""
    host: str = Field(..., description="Server host")
    """Server host"""
    port: int = Field(..., description="Server port")
    """Server port"""
    base_url: str = Field(..., description="Base URL")
    """Base URL"""

    class Config:
        extra = "ignore"