# Code generated by schema2code at 2025-10-20 19:11:09. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class SummarizationConfig(BaseModel):
    """Conversation summarization settings"""
    enabled: bool = Field(..., description="Whether summarization is enabled")
    """Whether summarization is enabled"""
    messages_before_summary: int = Field(..., description="Number of messages before summary")
    """Number of messages before summary"""
    summaries_before_consolidation: int = Field(..., description="Number of summaries before consolidation")
    """Number of summaries before consolidation"""
    embedding_dimension: int = Field(..., description="Embedding dimension")
    """Embedding dimension"""
    max_summary_levels: int = Field(..., description="Maximum summary levels")
    """Maximum summary levels"""
    summary_weight_coefficient: float = Field(..., description="Summary weight coefficient")
    """Summary weight coefficient"""

    class Config:
        extra = "ignore"