# Code generated by schema2code at 2025-10-20 19:11:11. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .analysis_depth import AnalysisDepth
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ToolAnalysisRequest(BaseModel):
    """Request for analyzing if tools are needed for a user message"""
    user_message: str = Field(..., description="The user's message text to analyze")
    """The user's message text to analyze"""
    conversation_id: int = Field(..., description="ID of the conversation context", ge=1)
    """ID of the conversation context"""
    analysis_depth: Optional[AnalysisDepth] = Field(default='detailed', description="Depth of analysis to perform")
    """Depth of analysis to perform"""

    class Config:
        extra = "ignore"