# Code generated by schema2code at 2025-10-20 19:11:11. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .dynamic_tool import DynamicTool
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ToolNeeds(BaseModel):
    """Schema for tool needs analysis"""
    available_tools: List[str] = Field(..., description="List of available tool names")
    """List of available tool names"""
    needs_dynamic_tool: bool = Field(...)
    dynamic_tool: Optional[DynamicTool] = Field(default=None)

    class Config:
        extra = "ignore"