# Code generated by schema2code at 2025-10-20 19:11:12. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class User(BaseModel):
    """User represents a user of the system"""
    id: str = Field(..., description="Unique identifier for the user")
    """Unique identifier for the user"""
    username: str = Field(..., description="Username of the user")
    """Username of the user"""
    uid: str = Field(..., description="User identification number")
    """User identification number"""
    created_at: datetime = Field(..., description="Timestamp of when the user was created")
    """Timestamp of when the user was created"""

    class Config:
        extra = "ignore"