# Code generated by schema2code at 2025-10-20 19:10:46. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class AuthConfig(BaseModel):
    """Authentication configuration"""
    jwks_uri: str = Field(..., description="JWKS URI")
    """JWKS URI"""
    audience: str = Field(..., description="Audience")
    """Audience"""
    client_id: str = Field(..., description="Client ID")
    """Client ID"""
    client_secret: str = Field(..., description="Client secret")
    """Client secret"""

    class Config:
        extra = "ignore"