# Code generated by schema2code at 2025-10-20 19:10:45. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .conversation import Conversation
from .image_metadata import ImageMetadata
from .intent import Intent
from .message import Message
from .message_content import MessageContent
from .message_content_type import MessageContentType
from .message_role import MessageRole
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ConversationCtx(BaseModel):
    """Manages context for a conversation, including messages, summaries, and retrieved memories. Provides methods for adding messages, summarizing conversations, and retrieving relevant context.
"""
    messages: List[Message] = Field(..., description="List of messages in the conversation")
    """List of messages in the conversation"""
    notes: List[str] = Field(..., description="List of notes related to the conversation")
    """List of notes related to the conversation"""
    images: List[ImageMetadata] = Field(..., description="List of images associated with the conversation")
    """List of images associated with the conversation"""
    conversation: Conversation = Field(..., description="The conversation object")
    """The conversation object"""
    current_user_message: Optional[Message] = Field(default=None, description="The current message from the user")
    """The current message from the user"""
    intent: Optional[Intent] = Field(default=None, description="The intent detected from the user's message")
    """The intent detected from the user's message"""

    class Config:
        extra = "ignore"