# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class DatabaseConfig(BaseModel):
    """Database configuration"""
    host: str = Field(..., description="Database host")
    """Database host"""
    port: int = Field(..., description="Database port")
    """Database port"""
    user: str = Field(..., description="Database user")
    """Database user"""
    password: str = Field(..., description="Database password")
    """Database password"""
    dbname: str = Field(..., description="Database name")
    """Database name"""
    sslmode: str = Field(..., description="SSL mode")
    """SSL mode"""
    connection_string: str = Field(..., description="Connection string")
    """Connection string"""

    class Config:
        extra = "ignore"