# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class EventStreamConfig(BaseModel):
    """Configuration schema for event stream processing"""
    thinking_phase_initial: bool = Field(default=True, description="Initial thinking phase flag")
    """Initial thinking phase flag"""
    max_content_length: int = Field(default=50000, description="Maximum content length allowed", ge=0)
    """Maximum content length allowed"""
    repetition_buffer_chars: int = Field(default=400, description="Buffer size for repetition detection in characters", ge=0)
    """Buffer size for repetition detection in characters"""
    ngram_min: int = Field(default=3, description="Minimum n-gram size", ge=1)
    """Minimum n-gram size"""
    ngram_max: int = Field(default=6, description="Maximum n-gram size", ge=1)
    """Maximum n-gram size"""
    ngram_repeat_threshold: int = Field(default=2, description="Number of prior occurrences to consider repetitive", ge=0)
    """Number of prior occurrences to consider repetitive"""
    stutter_window_words: int = Field(default=16, description="Window size for stutter detection in words", ge=1)
    """Window size for stutter detection in words"""
    stutter_unique_ratio_threshold: float = Field(default=0.25, description="Threshold for unique ratio in stutter window (≤ 25% unique)", ge=0, le=1)
    """Threshold for unique ratio in stutter window (≤ 25% unique)"""
    max_repetitions: int = Field(default=6, description="Maximum allowed repetitions", ge=0)
    """Maximum allowed repetitions"""
    dedup_last_hashes: int = Field(default=8, description="Number of last hashes to keep for deduplication", ge=0)
    """Number of last hashes to keep for deduplication"""

    class Config:
        extra = "ignore"