# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class GenerateResponse(BaseModel):
    """GenerateResponse represents a request to the Ollama embeddings API"""
    model: str = Field(...)
    created_at: Optional[str] = Field(default=None)
    response: str = Field(...)
    done: bool = Field(...)
    done_reason: Optional[str] = Field(default=None)
    context: Optional[List[int]] = Field(default=None, description="context IDs for the response")
    """context IDs for the response"""
    prompt_eval_count: Optional[int] = Field(default=None)
    prompt_eval_duration: Optional[float] = Field(default=None)
    eval_count: Optional[int] = Field(default=None)
    eval_duration: Optional[float] = Field(default=None)
    total_duration: Optional[float] = Field(default=None)
    load_duration: Optional[float] = Field(default=None)

    class Config:
        extra = "ignore"