# Code generated by schema2code at 2025-10-20 19:10:58. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class InternalConfig(BaseModel):
    """Configuration for internal services, including API keys and allowed IPs."""
    APIKey: str = Field(..., description="API key for internal service auth")
    """API key for internal service auth"""
    AllowedIPs: str = Field(..., description="Comma-separated list of allowed IPs")
    """Comma-separated list of allowed IPs"""

    class Config:
        extra = "ignore"