# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Intent(BaseModel):
    """Represents the intent detected from a user's message"""
    web_search: Optional[bool] = Field(default=None, description="Indicates if the intent involves a web search")
    """Indicates if the intent involves a web search"""
    memory: Optional[bool] = Field(default=None, description="Indicates if the intent involves memory retrieval")
    """Indicates if the intent involves memory retrieval"""
    deep_research: Optional[bool] = Field(default=None, description="Indicates if the intent involves deep research")
    """Indicates if the intent involves deep research"""
    image_generation: Optional[bool] = Field(default=None, description="Indicates if the intent involves image generation")
    """Indicates if the intent involves image generation"""
    statically_discovered: Optional[bool] = Field(default=None, description="Indicates if the intent was statically discovered")
    """Indicates if the intent was statically discovered"""

    class Config:
        extra = "ignore"