# Code generated by schema2code at 2025-09-19 14:17:29. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .lang_chain_message import LangChainMessage
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class LangGraphState(BaseModel):
    """Strongly typed state for LangGraph workflows."""
    messages: List[LangChainMessage] = Field(..., description="Sequence of messages")
    """Sequence of messages"""
    user_input: str = Field(..., description="Latest user input")
    """Latest user input"""
    error_count: int = Field(default=0, description="Number of errors encountered during workflow execution")
    """Number of errors encountered during workflow execution"""
    max_iterations: int = Field(default=10, description="Maximum number of iterations allowed in the workflow")
    """Maximum number of iterations allowed in the workflow"""
    current_iteration: int = Field(default=0, description="Current iteration count in the workflow execution")
    """Current iteration count in the workflow execution"""
    tools_used: List[str] = Field(default_factory=lambda: [], description="List of tools or functions that have been used in the workflow")
    """List of tools or functions that have been used in the workflow"""
    intermediate_results: Dict[str, Any] = Field(default_factory=lambda: {}, description="Storage for intermediate computation results during workflow execution")
    """Storage for intermediate computation results during workflow execution"""

    class Config:
        extra = "ignore"