# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class LangGraphNodeState(BaseModel):
    """State for individual nodes in LangGraph workflows"""
    node_id: str = Field(..., description="Unique identifier for the node")
    """Unique identifier for the node"""
    node_type: str = Field(..., description="Type of the node")
    """Type of the node"""
    input_data: Optional[Dict[str, Any]] = Field(default=None, description="Input data for the node")
    """Input data for the node"""
    output_data: Optional[Dict[str, Any]] = Field(default=None, description="Output data from the node")
    """Output data from the node"""
    execution_time_ms: Optional[float] = Field(default=None, description="Time taken to execute this node", ge=0)
    """Time taken to execute this node"""
    error_count: Optional[int] = Field(default=None, description="Number of errors encountered", ge=0)
    """Number of errors encountered"""
    retry_count: Optional[int] = Field(default=None, description="Number of retries attempted", ge=0)
    """Number of retries attempted"""

    class Config:
        extra = "ignore"