# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class LoraWeight(BaseModel):
    """LoraWeight contains information about a LoRA weight file"""
    id: str = Field(..., description="Unique identifier for the LoRA weight")
    """Unique identifier for the LoRA weight"""
    name: str = Field(..., description="Name of the LoRA weight")
    """Name of the LoRA weight"""
    parent_model: str = Field(..., description="Identifier of the parent model this LoRA weight is associated with")
    """Identifier of the parent model this LoRA weight is associated with"""
    weight_name: Optional[str] = Field(default=None, description="Name of the weight file (e.g., 'lora.safetensors')")
    """Name of the weight file (e.g., 'lora.safetensors')"""
    adapter_name: Optional[str] = Field(default=None, description="Name of the adapter (e.g., 'uncensored')")
    """Name of the adapter (e.g., 'uncensored')"""

    class Config:
        extra = "ignore"