# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class MemorySource(str, Enum):
    """Source type for a memory"""
    SUMMARY = 'summary'
    """Memory type for conversation summaries"""
    MESSAGE = 'message'
    """Memory type for conversation messages"""
    SEARCH = 'search'
    """Memory type for search topic syntheses"""