# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class MemoryConfig(BaseModel):
    """Memory retrieval settings for semantic search and embedding operations"""
    enabled: bool = Field(default=True, description="Whether memory retrieval is enabled")
    """Whether memory retrieval is enabled"""
    limit: int = Field(default=5, description="Maximum number of memories to retrieve", ge=1, le=50)
    """Maximum number of memories to retrieve"""
    enable_cross_user: bool = Field(default=False, description="Enable cross-user memory retrieval")
    """Enable cross-user memory retrieval"""
    enable_cross_conversation: bool = Field(default=True, description="Enable cross-conversation memory retrieval")
    """Enable cross-conversation memory retrieval"""
    similarity_threshold: float = Field(default=0.7, description="Minimum similarity threshold for memory matching (0.0 to 1.0)", ge=0.0, le=1.0)
    """Minimum similarity threshold for memory matching (0.0 to 1.0)"""
    always_retrieve: bool = Field(default=False, description="Always retrieve memories regardless of query content")
    """Always retrieve memories regardless of query content"""
    timeout: float = Field(default=10.0, description="Memory retrieval timeout in seconds", ge=1.0, le=60.0)
    """Memory retrieval timeout in seconds"""

    class Config:
        extra = "ignore"