# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class MessageContentType(str, Enum):
    """Type of content in a message or streaming chunk"""
    TEXT = 'text'
    IMAGE = 'image'
    TOOL_CALL = 'tool_call'
    TOOL_RESULT = 'tool_result'
    IMAGE_GENERATION = 'image_generation'
    AUDIO = 'audio'
    VIDEO = 'video'
    IMAGE_EDIT = 'image_edit'
    FILE = 'file'
    THINKING = 'thinking'
    ERROR_CONTENT = 'error_content'
    METADATA = 'metadata'