# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
import uuid
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ModelProfileConfig(BaseModel):
    """Model profile configuration"""
    primary_profile_id: uuid.UUID = Field(..., description="Primary profile ID")
    """Primary profile ID"""
    summarization_profile_id: uuid.UUID = Field(..., description="Summarization profile ID")
    """Summarization profile ID"""
    master_summary_profile_id: uuid.UUID = Field(..., description="Master summary profile ID")
    """Master summary profile ID"""
    brief_summary_profile_id: uuid.UUID = Field(..., description="Brief summary profile ID")
    """Brief summary profile ID"""
    key_points_profile_id: uuid.UUID = Field(..., description="Key points profile ID")
    """Key points profile ID"""
    improvement_profile_id: uuid.UUID = Field(..., description="Improvement profile ID")
    """Improvement profile ID"""
    analysis_profile_id: uuid.UUID = Field(..., description="Analysis profile ID")
    """Analysis profile ID"""
    memory_retrieval_profile_id: uuid.UUID = Field(..., description="Memory retrieval profile ID")
    """Memory retrieval profile ID"""
    self_critique_profile_id: uuid.UUID = Field(..., description="Self-critique profile ID")
    """Self-critique profile ID"""
    research_task_profile_id: uuid.UUID = Field(..., description="Research task profile ID")
    """Research task profile ID"""
    research_plan_profile_id: uuid.UUID = Field(..., description="Research plan profile ID")
    """Research plan profile ID"""
    research_consolidation_profile_id: uuid.UUID = Field(..., description="Research consolidation profile ID")
    """Research consolidation profile ID"""
    research_analysis_profile_id: uuid.UUID = Field(..., description="Research analysis profile ID")
    """Research analysis profile ID"""
    embedding_profile_id: uuid.UUID = Field(..., description="Embedding profile ID")
    """Embedding profile ID"""
    formatting_profile_id: uuid.UUID = Field(..., description="Formatting profile ID")
    """Formatting profile ID"""
    image_generation_prompt_profile_id: uuid.UUID = Field(..., description="Image generation prompt profile ID")
    """Image generation prompt profile ID"""
    image_generation_profile_id: uuid.UUID = Field(..., description="Image generation profile ID")
    """Image generation profile ID"""
    engineering_profile_id: uuid.UUID = Field(..., description="Engineering profile ID")
    """Engineering profile ID"""
    reranking_profile_id: uuid.UUID = Field(..., description="Reranking profile ID")
    """Reranking profile ID"""

    class Config:
        extra = "ignore"