# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ModelDetails(BaseModel):
    """ModelDetails contains additional information about a model"""
    parent_model: Optional[str] = Field(default=None, description="Identifier of the parent model if this is a derivative")
    """Identifier of the parent model if this is a derivative"""
    format: str = Field(..., description="Format of the model file (e.g., gguf)")
    """Format of the model file (e.g., gguf)"""
    gguf_file: Optional[str] = Field(default=None, description="Path to the GGUF file if applicable")
    """Path to the GGUF file if applicable"""
    family: str = Field(..., description="Primary model family this belongs to (e.g., llama, phi3)")
    """Primary model family this belongs to (e.g., llama, phi3)"""
    families: List[str] = Field(..., description="All model families this belongs to")
    """All model families this belongs to"""
    parameter_size: str = Field(..., description="Size of model parameters (e.g., '7.2B')")
    """Size of model parameters (e.g., '7.2B')"""
    quantization_level: Optional[str] = Field(default=None, description="Level of quantization applied to the model (e.g., 'Q4_0')")
    """Level of quantization applied to the model (e.g., 'Q4_0')"""
    dtype: Optional[str] = Field(default=None, description="Data type of the model (e.g., 'float16', 'bfloat16')")
    """Data type of the model (e.g., 'float16', 'bfloat16')"""
    precision: Optional[str] = Field(default=None, description="Precision of the model (e.g., 'fp16', 'bf16')")
    """Precision of the model (e.g., 'fp16', 'bf16')"""
    specialization: Optional[str] = Field(default=None, description="Specialization of the model (e.g., 'LoRA', 'Embedding', 'TextToImage', 'Audio', 'Vision')")
    """Specialization of the model (e.g., 'LoRA', 'Embedding', 'TextToImage', 'Audio', 'Vision')"""
    description: Optional[str] = Field(default=None, description="Description of the model")
    """Description of the model"""
    weight: Optional[float] = Field(default=None, description="Weight of the model (applies to LoRA models)")
    """Weight of the model (applies to LoRA models)"""

    class Config:
        extra = "ignore"