# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class ModelTask(str, Enum):
    """ModelTask represents the task associated with a machine learning model"""
    TEXTTOTEXT = 'TextToText'
    TEXTTOIMAGE = 'TextToImage'
    IMAGETOTEXT = 'ImageToText'
    IMAGETOIMAGE = 'ImageToImage'
    TEXTTOAUDIO = 'TextToAudio'
    AUDIOTOTEXT = 'AudioToText'
    TEXTTOVIDEO = 'TextToVideo'
    VIDEOTOTEXT = 'VideoToText'
    TEXTTOSPEECH = 'TextToSpeech'
    SPEECHTOTEXT = 'SpeechToText'
    TEXTTOEMBEDDINGS = 'TextToEmbeddings'
    VISIONTEXTTOTEXT = 'VisionTextToText'
    IMAGETEXTTOIMAGE = 'ImageTextToImage'
    TEXTTORANKING = 'TextToRanking'