# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .lora_weight import LoraWeight
from .model_details import ModelDetails
from .model_provider import ModelProvider
from .model_task import ModelTask
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Model(BaseModel):
    """Model represents a machine learning model used for generating responses"""
    id: Optional[str] = Field(default=None, description="Unique identifier for the model")
    """Unique identifier for the model"""
    name: str = Field(..., description="Display name of the model")
    """Display name of the model"""
    model: str = Field(..., description="Identifier used to reference the model")
    """Identifier used to reference the model"""
    task: ModelTask = Field(..., description="Type of task the model is designed for (e.g., \"TextToText\", \"TextToImage\")")
    """Type of task the model is designed for (e.g., \"TextToText\", \"TextToImage\")"""
    modified_at: str = Field(..., description="Timestamp of when the model was last modified")
    """Timestamp of when the model was last modified"""
    size: int = Field(..., description="Size of the model in bytes")
    """Size of the model in bytes"""
    digest: str = Field(..., description="Hash digest identifying the model version")
    """Hash digest identifying the model version"""
    details: ModelDetails = Field(..., description="Additional information about the model")
    """Additional information about the model"""
    pipeline: Optional[str] = Field(default=None, description="Pipeline type used for the model (e.g., \"sd3\", \"sdxl\")")
    """Pipeline type used for the model (e.g., \"sd3\", \"sdxl\")"""
    lora_weights: Optional[List[LoraWeight]] = Field(default=None, description="List of LoRA weights associated with the model")
    """List of LoRA weights associated with the model"""
    provider: ModelProvider = Field(..., description="Provider or runtime of the model (e.g., \"llama.cpp\", \"hf\", \"openai\")")
    """Provider or runtime of the model (e.g., \"llama.cpp\", \"hf\", \"openai\")"""

    class Config:
        extra = "ignore"