# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .model_profile_type import ModelProfileType
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class NodeMetadata(BaseModel):
    """Metadata structure for workflow node execution tracking"""
    node_name: str = Field(..., description="Human-readable name of the node")
    """Human-readable name of the node"""
    node_id: str = Field(..., description="Unique identifier for this specific node instance")
    """Unique identifier for this specific node instance"""
    node_type: str = Field(..., description="Class name of the node for type identification")
    """Class name of the node for type identification"""
    execution_time: Optional[datetime] = Field(default=None)
    user_id: Optional[str] = Field(default=None, description="User identifier associated with this execution")
    """User identifier associated with this execution"""
    conversation_id: Optional[int] = Field(default=None, description="Conversation identifier for this execution context")
    """Conversation identifier for this execution context"""
    profile_type: Optional[ModelProfileType] = Field(default=None, description="Model profile type for pipeline execution")
    """Model profile type for pipeline execution"""
    streaming: Optional[bool] = Field(default=None, description="Whether this execution uses streaming responses")
    """Whether this execution uses streaming responses"""
    is_cached: Optional[bool] = Field(default=None, description="Whether this execution uses a cached pipeline")
    """Whether this execution uses a cached pipeline"""
    cache_key: Optional[str] = Field(default=None, description="Cache key used for pipeline caching")
    """Cache key used for pipeline caching"""
    tool_count: Optional[int] = Field(default=None, description="Number of tools available or executed", ge=0)
    """Number of tools available or executed"""

    class Config:
        extra = "ignore"