# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class PipelinePriority(Enum):
    """Pipeline priority levels for cache eviction and resource management"""
    LOW = 1
    MEDIUM = 5
    NORMAL = 10
    HIGH = 11
    CRITICAL = 20