# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class PipelineMetrics(BaseModel):
    """Performance metrics for pipeline execution"""
    total_tokens: Optional[int] = Field(default=None, description="Total tokens processed", ge=0)
    """Total tokens processed"""
    processing_time_seconds: Optional[float] = Field(default=None, description="Total processing time in seconds", ge=0)
    """Total processing time in seconds"""
    memory_usage_mb: Optional[float] = Field(default=None, description="Peak memory usage in MB", ge=0)
    """Peak memory usage in MB"""
    tool_calls_made: Optional[int] = Field(default=None, description="Number of tool calls made", ge=0)
    """Number of tool calls made"""
    cache_hits: Optional[int] = Field(default=None, description="Number of cache hits", ge=0)
    """Number of cache hits"""
    cache_misses: Optional[int] = Field(default=None, description="Number of cache misses", ge=0)
    """Number of cache misses"""

    class Config:
        extra = "ignore"