# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .execution_state import ExecutionState
from .resource_usage import ResourceUsage
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class PipelineExecutionContext(BaseModel):
    """Context for tracking pipeline execution lifecycle"""
    pipeline_id: str = Field(..., description="Unique identifier for the pipeline execution")
    """Unique identifier for the pipeline execution"""
    task_name: str = Field(..., description="Name of the task being executed")
    """Name of the task being executed"""
    user_id: str = Field(..., description="ID of the user initiating the pipeline")
    """ID of the user initiating the pipeline"""
    model_id: str = Field(..., description="ID of the model being used")
    """ID of the model being used"""
    profile_id: str = Field(..., description="ID of the model profile being used")
    """ID of the model profile being used"""
    task_type: str = Field(..., description="Type of task being executed")
    """Type of task being executed"""
    arguments: Dict[str, Any] = Field(..., description="Arguments passed to the pipeline")
    """Arguments passed to the pipeline"""
    start_time: datetime = Field(..., description="When the pipeline execution started")
    """When the pipeline execution started"""
    end_time: Optional[datetime] = Field(default=None, description="When the pipeline execution ended")
    """When the pipeline execution ended"""
    execution_state: ExecutionState = Field(..., description="Current execution state")
    """Current execution state"""
    result: Optional[Dict[str, Any]] = Field(default=None, description="Pipeline execution result")
    """Pipeline execution result"""
    error_message: Optional[str] = Field(default=None, description="Error message if execution failed")
    """Error message if execution failed"""
    timeout_seconds: Optional[float] = Field(default=None, description="Timeout for pipeline execution in seconds", ge=0.1)
    """Timeout for pipeline execution in seconds"""
    resource_usage: Optional[ResourceUsage] = Field(default=None, description="Resource usage tracking")
    """Resource usage tracking"""

    class Config:
        extra = "ignore"