# Code generated by schema2code at 2025-10-20 19:10:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .pipeline_metrics import PipelineMetrics
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class PipelineExecutionState(BaseModel):
    """State tracking for pipeline execution"""
    pipeline_id: str = Field(..., description="Unique identifier for the pipeline execution")
    """Unique identifier for the pipeline execution"""
    conversation_id: int = Field(..., description="Associated conversation ID")
    """Associated conversation ID"""
    user_id: str = Field(..., description="User ID for the execution")
    """User ID for the execution"""
    status: str = Field(..., description="Current execution status")
    """Current execution status"""
    start_time: datetime = Field(..., description="When execution started")
    """When execution started"""
    end_time: Optional[datetime] = Field(default=None, description="When execution completed")
    """When execution completed"""
    error_message: Optional[str] = Field(default=None, description="Error message if execution failed")
    """Error message if execution failed"""
    metrics: Optional[PipelineMetrics] = Field(default=None)

    class Config:
        extra = "ignore"