# Code generated by schema2code at 2025-10-20 19:11:00. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class PreferencesConfig(BaseModel):
    """User preferences"""
    default_profile_id: Optional[str] = Field(default=None, description="Default profile ID")
    """Default profile ID"""
    theme: Optional[str] = Field(default=None, description="Theme")
    """Theme"""
    font_size: Optional[int] = Field(default=None, description="Font size")
    """Font size"""
    notifications_on: Optional[bool] = Field(default=None, description="Notifications enabled")
    """Notifications enabled"""
    language: Optional[str] = Field(default=None, description="Language")
    """Language"""

    class Config:
        extra = "ignore"