# Code generated by schema2code at 2025-10-20 19:11:00. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class RabbitmqConfig(BaseModel):
    enabled: bool = Field(..., description="Whether RabbitMQ is enabled")
    """Whether RabbitMQ is enabled"""
    host: str = Field(..., description="RabbitMQ host")
    """RabbitMQ host"""
    port: int = Field(..., description="RabbitMQ port")
    """RabbitMQ port"""
    user: str = Field(..., description="RabbitMQ user")
    """RabbitMQ user"""
    password: str = Field(..., description="RabbitMQ password")
    """RabbitMQ password"""
    vhost: str = Field(..., description="RabbitMQ virtual host")
    """RabbitMQ virtual host"""

    class Config:
        extra = "ignore"