# Code generated by schema2code at 2025-10-20 19:11:01. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class RefinementConfig(BaseModel):
    """Response refinement settings"""
    enable_response_filtering: bool = Field(..., description="Enable response filtering")
    """Enable response filtering"""
    enable_response_critique: bool = Field(..., description="Enable response critique")
    """Enable response critique"""

    class Config:
        extra = "ignore"