# Code generated by schema2code at 2025-10-20 19:11:04. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ResearchQuestion(BaseModel):
    """Sub-question in a research plan"""
    id: int = Field(..., description="Unique identifier for the question")
    """Unique identifier for the question"""
    question: str = Field(..., description="The question to investigate")
    """The question to investigate"""
    keywords: List[str] = Field(..., description="Keywords relevant to the question")
    """Keywords relevant to the question"""

    class Config:
        extra = "ignore"