# Code generated by schema2code at 2025-10-20 19:11:04. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .research_question import ResearchQuestion
from .research_question_result import ResearchQuestionResult
from .research_subtask import ResearchSubtask
from .research_task_status import ResearchTaskStatus
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ResearchTask(BaseModel):
    """ResearchTask represents a deep research task"""
    id: int = Field(..., description="Unique identifier for the research task")
    """Unique identifier for the research task"""
    user_id: str = Field(..., description="Id of the user who owns the task")
    """Id of the user who owns the task"""
    query: str = Field(..., description="Original research query")
    """Original research query"""
    conversation_id: Optional[int] = Field(default=None, description="Id of the conversation associated with this task if any")
    """Id of the conversation associated with this task if any"""
    status: ResearchTaskStatus = Field(..., description="Current status of the research task")
    """Current status of the research task"""
    error_message: Optional[str] = Field(default=None, description="Error message if task failed")
    """Error message if task failed"""
    plan: Optional[str] = Field(default=None, description="Research plan with sub-questions")
    """Research plan with sub-questions"""
    embedding: Optional[List[float]] = Field(default=None, description="The reasearch plan's embedding vector")
    """The reasearch plan's embedding vector"""
    subtasks: Optional[List[ResearchSubtask]] = Field(default=None, description="List of subtasks associated with this research task")
    """List of subtasks associated with this research task"""
    created_at: datetime = Field(..., description="Timestamp of when the task was created")
    """Timestamp of when the task was created"""
    updated_at: datetime = Field(..., description="Timestamp of when the task was last updated")
    """Timestamp of when the task was last updated"""
    completed_at: Optional[datetime] = Field(default=None, description="Timestamp of when the task was completed")
    """Timestamp of when the task was completed"""

    class Config:
        extra = "ignore"