# Code generated by schema2code at 2025-10-20 19:11:07. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class SearchTopicSynthesis(BaseModel):
    """Schema for synthesizing search topics"""
    urls: List[str] = Field(..., description="List of URLs used to synthesize topics")
    """List of URLs used to synthesize topics"""
    topics: List[str] = Field(..., description="List of topics synthesized from the URLs")
    """List of topics synthesized from the URLs"""
    synthesis: str = Field(..., description="The summary or synthesis of the topics from the content at the provided URLs")
    """The summary or synthesis of the topics from the content at the provided URLs"""
    created_at: datetime = Field(..., description="The timestamp when the synthesis was created")
    """The timestamp when the synthesis was created"""
    id: Optional[int] = Field(default=None, description="The unique identifier for the synthesis")
    """The unique identifier for the synthesis"""
    conversation_id: int = Field(..., description="The ID of the conversation associated with this synthesis")
    """The ID of the conversation associated with this synthesis"""

    class Config:
        extra = "ignore"