# Code generated by schema2code at 2025-10-20 19:11:09. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .socket_stage_type import SocketStageType
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class SocketStatusUpdate(BaseModel):
    """SocketStatusUpdate represents a status update message sent via WebSocket"""
    user_id: str = Field(..., description="The ID of the user associated with the status update.")
    """The ID of the user associated with the status update."""
    type: str = Field(..., description="The type of status update (info, warning, error).")
    """The type of status update (info, warning, error)."""
    stage: SocketStageType = Field(..., description="The current processing stage.")
    """The current processing stage."""
    message: Optional[str] = Field(default=None, description="Optional detailed message.")
    """Optional detailed message."""
    progress: int = Field(..., description="0-100 progress percentage.", ge=0, le=100)
    """0-100 progress percentage."""
    done: bool = Field(..., description="Whether processing is complete.")
    """Whether processing is complete."""

    class Config:
        extra = "ignore"