# Code generated by schema2code at 2025-10-20 19:11:10. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Summary(BaseModel):
    """Summary represents a consolidated summary of messages or other summaries"""
    content: str = Field(..., description="Text content of the summary")
    """Text content of the summary"""
    level: int = Field(..., description="Level of the summary in the hierarchy")
    """Level of the summary in the hierarchy"""
    id: int = Field(..., description="Unique identifier for the summary")
    """Unique identifier for the summary"""
    conversation_id: int = Field(..., description="Id of the conversation this summary belongs to")
    """Id of the conversation this summary belongs to"""
    source_ids: List[int] = Field(..., description="IDs of the source messages or summaries")
    """IDs of the source messages or summaries"""
    created_at: datetime = Field(..., description="Timestamp of when the summary was created")
    """Timestamp of when the summary was created"""

    class Config:
        extra = "ignore"