# Code generated by schema2code at 2025-10-07 10:30:14. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .circuit_breaker_config import CircuitBreakerConfig
from .context_window_config import ContextWindowConfig
from .event_stream_config import EventStreamConfig
from .gpu_config import GPUConfig
from .image_generation_config import ImageGenerationConfig
from .memory_config import MemoryConfig
from .model_profile_config import ModelProfileConfig
from .preferences_config import PreferencesConfig
from .refinement_config import RefinementConfig
from .summarization_config import SummarizationConfig
from .tool_config import ToolConfig
from .web_search_config import WebSearchConfig
from .workflow_config import WorkflowConfig
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class UserConfig(BaseModel):
    """User-specific configuration"""
    user_id: str = Field(..., description="User ID")
    """User ID"""
    summarization: SummarizationConfig = Field(...)
    memory: MemoryConfig = Field(...)
    web_search: WebSearchConfig = Field(...)
    preferences: PreferencesConfig = Field(...)
    model_profiles: ModelProfileConfig = Field(...)
    refinement: RefinementConfig = Field(...)
    image_generation: ImageGenerationConfig = Field(...)
    circuit_breaker: CircuitBreakerConfig = Field(...)
    gpu_config: GPUConfig = Field(...)
    workflow: WorkflowConfig = Field(...)
    tool: ToolConfig = Field(...)
    event_stream: Optional[EventStreamConfig] = Field(default=None)
    context_window: ContextWindowConfig = Field(...)

    class Config:
        extra = "ignore"