# Code generated by schema2code at 2025-10-20 19:11:13. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class WebSocketConnection(BaseModel):
    """WebSocketConnection represents an active WebSocket connection"""
    id: str = Field(..., description="Unique identifier for the connection")
    """Unique identifier for the connection"""
    user_id: str = Field(..., description="Identifier of the user associated with the connection")
    """Identifier of the user associated with the connection"""
    type: str = Field(..., description="Type of WebSocket connection (e.g., chat, image, status)")
    """Type of WebSocket connection (e.g., chat, image, status)"""
    conn: Optional[Any] = Field(default=None, description="The WebSocket connection object (represented as string)")
    """The WebSocket connection object (represented as string)"""
    created_at: datetime = Field(..., description="Timestamp indicating when the connection was established")
    """Timestamp indicating when the connection was established"""

    class Config:
        extra = "ignore"