# Code generated by schema2code at 2025-10-20 19:11:12. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class WebSearchConfig(BaseModel):
    """Comprehensive web search settings for SearxNG integration"""
    enabled: bool = Field(default=True, description="Whether web search is enabled")
    """Whether web search is enabled"""
    auto_detect: bool = Field(default=True, description="Auto-detect web search needs from user queries")
    """Auto-detect web search needs from user queries"""
    max_results: int = Field(default=5, description="Maximum number of search results to return", ge=1, le=20)
    """Maximum number of search results to return"""
    include_results: bool = Field(default=True, description="Include full search results in response")
    """Include full search results in response"""
    max_urls_deep: int = Field(default=3, description="Maximum number of URLs to deep crawl for content extraction", ge=0, le=10)
    """Maximum number of URLs to deep crawl for content extraction"""
    engines: List[str] = Field(default_factory=lambda: ['google', 'bing', 'duckduckgo', 'startpage', 'github', 'arxiv', 'wikipedia'], description="List of SearxNG search engines to use")
    """List of SearxNG search engines to use"""
    categories: List[str] = Field(default_factory=lambda: ['general', 'news', 'science', 'it'], description="SearxNG search categories to include")
    """SearxNG search categories to include"""
    language: str = Field(default='en', description="Language for search results")
    """Language for search results"""
    safesearch: int = Field(default=0, description="Safe search level (0=off, 1=moderate, 2=strict)", ge=0, le=2)
    """Safe search level (0=off, 1=moderate, 2=strict)"""
    time_range: Optional[str] = Field(default='', description="Time range filter for results")
    """Time range filter for results"""
    searx_host: Optional[str] = Field(default='', description="SearxNG host URL (defaults to SEARX_HOST environment variable)")
    """SearxNG host URL (defaults to SEARX_HOST environment variable)"""
    timeout: Optional[float] = Field(default=30.0, description="Search timeout in seconds", ge=5.0, le=120.0)
    """Search timeout in seconds"""
    user_agent: Optional[str] = Field(default='LLMMLLab-WebSearch/1.0', description="Custom User-Agent string for requests")
    """Custom User-Agent string for requests"""
    enable_caching: Optional[bool] = Field(default=True, description="Enable result caching for performance")
    """Enable result caching for performance"""
    cache_ttl: Optional[int] = Field(default=300, description="Cache time-to-live in seconds", ge=60, le=3600)
    """Cache time-to-live in seconds"""
    max_content_length: Optional[int] = Field(default=5000, description="Maximum content length to fetch from URLs (in characters)", ge=1000, le=100000)
    """Maximum content length to fetch from URLs (in characters)"""

    class Config:
        extra = "ignore"