// Code generated by schema2code at 2025-09-18 13:18:21. DO NOT EDIT.


import { ModelParameters } from './ModelParameters';

import { Message } from './Message';



/**
 * ChatReq represents a request to the Ollama API
 */
export interface ChatReq {
  /**
   * Messages to send to the model, each message is a struct with role and content
   */
  messages: Message[];
  /**
   * If true, the response will be streamed back as a series of events
   */
  stream: boolean;
  /**
   * The format to return a response in. Format can be json or a JSON schema
   */
  format?: Record<string, unknown>;
  /**
   * The ID of the conversation this message belongs to
   */
  conversation_id: number;
  /**
   * Controls how long the model will stay loaded into memory
   */
  keep_alive?: number;
  /**
   * Additional model parameters listed in the documentation for the Modelfile such as temperature
   */
  options?: ModelParameters;
  /**
   * Tools to use for the request, if any
   */
  tools?: Record<string, unknown>[];
  /**
   * If true, the model will think before responding, useful for complex queries
   */
  think?: boolean;
}