// Code generated by schema2code at 2025-10-20 19:10:23. DO NOT EDIT.


import { Message } from './Message';



/**
 * ChatResponse represents a response from the chat API
 */
export interface ChatResponse {
  /**
   * Indicates whether the generation is complete
   */
  done: boolean;
  /**
   * The message content and metadata returned by the model
   */
  message?: Message;
  /**
   * Timestamp when the response was created
   */
  created_at?: Date;
  /**
   * Vectors representing the tokenized context (embeddings)
   */
  context?: number[][];
  /**
   * Specific indicator of how or why the generation finished
   */
  finish_reason?: 'stop' | 'length' | 'error' | 'load' | 'unload' | 'timeout' | 'cancel';
  /**
   * Total time taken for the entire generation process in milliseconds
   */
  total_duration?: number;
  /**
   * Time taken to load the model in milliseconds
   */
  load_duration?: number;
  /**
   * Number of tokens in the prompt that were evaluated
   */
  prompt_eval_count?: number;
  /**
   * Time taken to evaluate the prompt tokens in milliseconds
   */
  prompt_eval_duration?: number;
  /**
   * Total number of tokens evaluated
   */
  eval_count?: number;
  /**
   * Time taken for token evaluation in milliseconds
   */
  eval_duration?: number;
  /**
   * The thinking/reasoning process from the assistant before the response
   */
  thinking?: string;
  /**
   * Additional structured channels extracted from the response (tool calls, status, etc.)
   */
  channels?: Record<string, unknown>;
  /**
   * OBSERVER role messages that should be displayed as temporary floating notifications
   */
  observer_messages?: string[];
}