// Code generated by schema2code at 2025-10-20 19:10:32. DO NOT EDIT.


/**
 * Configuration for circuit breaker and timeout protection
 */
export interface CircuitBreakerConfig {
  /**
   * Base timeout in seconds
   */
  base_timeout?: number;
  /**
   * Extended timeout for deep research tasks
   */
  deep_research_timeout?: number;
  /**
   * Maximum number of retries before giving up
   */
  max_retries?: number;
  /**
   * Time in seconds before allowing retry after failure
   */
  cooldown_period?: number;
  /**
   * Enable or disable perplexity-based quality monitoring
   */
  enable_perplexity_guard?: boolean;
  /**
   * Enable or disable repetition detection entirely
   */
  enable_repetition_detection?: boolean;
  /**
   * Number of tokens to consider when calculating perplexity
   */
  perplexity_window?: number;
  /**
   * Perplexity threshold above which to trigger quality concerns
   */
  perplexity_threshold?: number;
  /**
   * Minimum average log probability threshold
   */
  avg_logprob_floor?: number;
  /**
   * N-gram size for repetition detection
   */
  repetition_ngram?: number;
  /**
   * Number of repetitions before triggering detection
   */
  repetition_threshold?: number;
  /**
   * Minimum number of tokens before starting quality evaluation
   */
  min_tokens_for_eval?: number;
  /**
   * Interval in tokens for logging perplexity metrics
   */
  perplexity_log_interval_tokens?: number;
  /**
   * Whether to log repetition detection events
   */
  log_repetition_events?: boolean;
  /**
   * N-gram size for tool generation repetition detection
   */
  tool_gen_repetition_ngram?: number;
  /**
   * Number of repetitions before triggering tool generation detection
   */
  tool_gen_repetition_threshold?: number;
}