// Code generated by schema2code at 2025-10-20 19:10:26. DO NOT EDIT.


/**
 * Request for generating an image
 */
export interface ImageGenerateRequest {
  /**
   * The prompt for image generation
   */
  prompt: string;
  /**
   * Width of the generated image
   */
  width?: number;
  /**
   * Height of the generated image
   */
  height?: number;
  /**
   * Number of inference steps
   */
  inference_steps?: number;
  /**
   * Guidance scale for image generation
   */
  guidance_scale?: number;
  /**
   * Whether to use low memory mode
   */
  low_memory_mode?: boolean;
  /**
   * Negative prompt for image generation
   */
  negative_prompt?: string;
  /**
   * Model to use for image generation
   */
  model: string;
  /**
   * List of LoRA models to apply to the image generation
   */
  loras?: string[];
  /**
   * ID of the image to use as a base for image generation (for img2img)
   */
  image_id?: number;
  /**
   * URL of the image to use as a base for image generation (for img2img)
   */
  url?: string;
  /**
   * Name of the file to save the generated image as
   */
  filename?: string;
}