// Code generated by schema2code at 2025-10-20 19:10:31. DO NOT EDIT.


/**
 * LoraWeight contains information about a LoRA weight file
 */
export interface LoraWeight {
  /**
   * Unique identifier for the LoRA weight
   */
  id: string;
  /**
   * Name of the LoRA weight
   */
  name: string;
  /**
   * Identifier of the parent model this LoRA weight is associated with
   */
  parent_model: string;
  /**
   * Name of the weight file (e.g., 'lora.safetensors')
   */
  weight_name?: string;
  /**
   * Name of the adapter (e.g., 'uncensored')
   */
  adapter_name?: string;
}