// Code generated by schema2code at 2025-10-07 10:30:10. DO NOT EDIT.


/**
 * Configuration for when to trigger memory search
 */
export interface TriggerConfig {
  /**
   * Minimum number of messages before triggering memory search
   */
  min_conversation_length: number;
  /**
   * Keywords that trigger memory search
   */
  keyword_triggers: string[];
  /**
   * Always perform memory search regardless of triggers
   */
  always_active: boolean;
}

/**
 * Configuration for semantic search operations
 */
export interface SearchConfig {
  /**
   * Maximum number of memories to retrieve
   */
  max_memories: number;
  /**
   * Minimum similarity score for memory inclusion
   */
  similarity_threshold: number;
  /**
   * Pair user messages with assistant responses
   */
  context_pairing: boolean;
  /**
   * Apply temporal decay to memory scores
   */
  temporal_decay: boolean;
  /**
   * Search across multiple conversations
   */
  cross_conversation: boolean;
}

/**
 * Configuration for memory optimization and formatting
 */
export interface OptimizationConfig {
  /**
   * Maximum tokens to use for memory context
   */
  max_token_budget: number;
  /**
   * Enable memory compression for token efficiency
   */
  compression_enabled: boolean;
  /**
   * Include metadata (timestamps, conversation IDs) in context
   */
  metadata_inclusion: boolean;
  /**
   * Style for formatting retrieved memories
   */
  formatting_style: 'structured' | 'narrative' | 'bulletpoints';
}

/**
 * Configuration for Memory Search RAG context extension strategy
 */
export interface MemorySearchRAGConfig {
  /**
   * Enable Memory Search RAG for semantic conversation history retrieval
   */
  enabled: boolean;
  /**
   * Configuration for when to trigger memory search
   */
  trigger_config: TriggerConfig;
  /**
   * Configuration for semantic search operations
   */
  search_config: SearchConfig;
  /**
   * Configuration for memory optimization and formatting
   */
  optimization_config: OptimizationConfig;
}