// Code generated by schema2code at 2025-10-20 19:10:32. DO NOT EDIT.


/**
 * Model profile configuration
 */
export interface ModelProfileConfig {
  /**
   * Primary profile ID
   */
  primary_profile_id: string;
  /**
   * Summarization profile ID
   */
  summarization_profile_id: string;
  /**
   * Master summary profile ID
   */
  master_summary_profile_id: string;
  /**
   * Brief summary profile ID
   */
  brief_summary_profile_id: string;
  /**
   * Key points profile ID
   */
  key_points_profile_id: string;
  /**
   * Improvement profile ID
   */
  improvement_profile_id: string;
  /**
   * Analysis profile ID
   */
  analysis_profile_id: string;
  /**
   * Memory retrieval profile ID
   */
  memory_retrieval_profile_id: string;
  /**
   * Self-critique profile ID
   */
  self_critique_profile_id: string;
  /**
   * Research task profile ID
   */
  research_task_profile_id: string;
  /**
   * Research plan profile ID
   */
  research_plan_profile_id: string;
  /**
   * Research consolidation profile ID
   */
  research_consolidation_profile_id: string;
  /**
   * Research analysis profile ID
   */
  research_analysis_profile_id: string;
  /**
   * Embedding profile ID
   */
  embedding_profile_id: string;
  /**
   * Formatting profile ID
   */
  formatting_profile_id: string;
  /**
   * Image generation prompt profile ID
   */
  image_generation_prompt_profile_id: string;
  /**
   * Image generation profile ID
   */
  image_generation_profile_id: string;
  /**
   * Engineering profile ID
   */
  engineering_profile_id: string;
  /**
   * Reranking profile ID
   */
  reranking_profile_id: string;
}