// Code generated by schema2code at 2025-10-20 19:10:34. DO NOT EDIT.


/**
 * Provider / runtime of the model (e.g., 'llama.cpp', 'hf', 'hugging face', 'openai', 'stable-diffusion.cpp', 'anthropic')
 */
export type ModelProvider = 'llama_cpp' | 'hf' | 'hugging_face' | 'openai' | 'stable_diffusion_cpp' | 'anthropic' | 'other';

/**
 * Constant values for ModelProvider
 */
export const ModelProviderValues = {
  /** llama_cpp */
  LLAMA_CPP: 'llama_cpp',
  /** hf */
  HF: 'hf',
  /** hugging_face */
  HUGGING_FACE: 'hugging_face',
  /** openai */
  OPENAI: 'openai',
  /** stable_diffusion_cpp */
  STABLE_DIFFUSION_CPP: 'stable_diffusion_cpp',
  /** anthropic */
  ANTHROPIC: 'anthropic',
  /** other */
  OTHER: 'other'
} as const;