// Code generated by schema2code at 2025-10-20 19:10:37. DO NOT EDIT.


import { SocketStageType } from './SocketStageType';

import { MessageType } from './MessageType';



/**
 * SocketMessage represents a response sent over WebSocket
 */
export interface SocketMessage {
  /**
   * Unique identifier for the message
   */
  id: string;
  /**
   * Content of the response
   */
  content?: string;
  /**
   * Error message if any
   */
  error?: string;
  /**
   * State of the chat session
   */
  state: SocketStageType;
  /**
   * Session identifier
   */
  session_id: string;
  /**
   * Timestamp of the response
   */
  timestamp: Date;
  /**
   * Type of message
   */
  type: MessageType;
  /**
   * Progress percentage of the response, if applicable
   */
  progress?: number;
  /**
   * Additional data related to the response, if any
   */
  data?: Record<string, unknown> | unknown[];
  /**
   * Identifier of the conversation associated with the response
   */
  conversation_id?: number;
}