// Code generated by schema2code at 2025-10-20 19:10:37. DO NOT EDIT.


/**
 * User-configurable tool execution settings
 */
export interface ToolConfig {
  /**
   * Similarity threshold for tool selection (0.0-1.0)
   */
  tool_similarity_threshold: number;
  /**
   * Threshold for tool modification/generation (0.0-1.0)
   */
  tool_modification_threshold: number;
  /**
   * Enable dynamic tool generation
   */
  enable_tool_generation: boolean;
  /**
   * Maximum retries for failed tool executions
   */
  max_tool_retries: number;
  /**
   * Default tool execution timeout in seconds
   */
  tool_timeout: number;
  /**
   * Enable tool result caching
   */
  enable_tool_caching: boolean;
  /**
   * Tool cache TTL in seconds
   */
  tool_cache_ttl: number;
  /**
   * Enable semantic tool selection
   */
  enable_semantic_search: boolean;
  /**
   * Number of top tools to consider in semantic search
   */
  search_top_k: number;
}