// Code generated by schema2code at 2025-10-20 19:10:38. DO NOT EDIT.


/**
 * Comprehensive web search settings for SearxNG integration
 */
export interface WebSearchConfig {
  /**
   * Whether web search is enabled
   */
  enabled: boolean;
  /**
   * Auto-detect web search needs from user queries
   */
  auto_detect: boolean;
  /**
   * Maximum number of search results to return
   */
  max_results: number;
  /**
   * Include full search results in response
   */
  include_results: boolean;
  /**
   * Maximum number of URLs to deep crawl for content extraction
   */
  max_urls_deep: number;
  /**
   * List of SearxNG search engines to use
   */
  engines: string[];
  /**
   * SearxNG search categories to include
   */
  categories: 'general' | 'news' | 'science' | 'it' | 'shopping' | 'images' | 'videos' | 'music' | 'files' | 'social'[];
  /**
   * Language for search results
   */
  language: 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'zh' | 'ja' | 'ko' | 'ru' | 'ar';
  /**
   * Safe search level (0=off, 1=moderate, 2=strict)
   */
  safesearch: number;
  /**
   * Time range filter for results
   */
  time_range?: '' | 'day' | 'week' | 'month' | 'year';
  /**
   * SearxNG host URL (defaults to SEARX_HOST environment variable)
   */
  searx_host?: string;
  /**
   * Search timeout in seconds
   */
  timeout?: number;
  /**
   * Custom User-Agent string for requests
   */
  user_agent?: string;
  /**
   * Enable result caching for performance
   */
  enable_caching?: boolean;
  /**
   * Cache time-to-live in seconds
   */
  cache_ttl?: number;
  /**
   * Maximum content length to fetch from URLs (in characters)
   */
  max_content_length?: number;
}