// Code generated by schema2code at 2025-10-20 19:10:41. DO NOT EDIT.


/**
 * User-configurable workflow settings
 */
export interface WorkflowConfig {
  /**
   * Enable workflow result caching
   */
  enable_workflow_caching: boolean;
  /**
   * Workflow cache TTL in seconds
   */
  workflow_cache_ttl: number;
  /**
   * Maximum number of tools to execute in parallel
   */
  max_parallel_tools: number;
  /**
   * Enable multi-agent workflow capabilities
   */
  enable_multi_agent: boolean;
  /**
   * Default workflow execution timeout in seconds
   */
  default_timeout: number;
  /**
   * Maximum context length for workflow processing
   */
  max_context_length: number;
  /**
   * Context trimming threshold (0.0-1.0)
   */
  context_trim_threshold: number;
  /**
   * Enable streaming workflow responses
   */
  enable_streaming: boolean;
  /**
   * Streaming buffer size in bytes
   */
  stream_buffer_size: number;
}