"""Update role to use enums for type safety

Revision ID: 4ac07ba2174a
Revises: 6692f1b7b4dd
Create Date: 2025-04-29 10:49:43.330937

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ac07ba2174a"
down_revision: str | None = "6692f1b7b4dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    op.execute("CREATE TYPE messagerole AS ENUM ('user', 'assistant', 'system')")
    op.alter_column(
        "messages",
        "role",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum("user", "assistant", "system", name="messagerole"),
        postgresql_using="role::messagerole",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "messages",
        "role",
        existing_type=sa.Enum("user", "assistant", "system", name="messagerole"),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.execute("DROP TYPE messagerole")
    # ### end Alembic commands ###
